### ISSUE TITLE
do not work with django 1.9.*

### ISSUE THREAD

**Issue by keiser1080** [stephenmcd/drum#32]
Hi, 

drum work on django version <= 1.8.12
`Performing system checks...

/home/keiser1080/.virtualenvs/pypy-env/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

System check identified some issues:

WARNINGS:
?: (mezzanine.core.W01) Please update your settings to use the TEMPLATES setting rather than the deprecated individual TEMPLATE_ settings. The latter are unsupported and correct behaviour is not guaranteed. Here's a suggestion based on on your existing configuration:

TEMPLATES = [{u'APP_DIRS': True,
              u'BACKEND': u'django.template.backends.django.DjangoTemplates',
              u'DIRS': (u'/home/keiser1080/dev/drumbase/templates',),
              u'OPTIONS': {u'builtins': [u'mezzanine.template.loader_tags'],
                           u'context_processors': (u'django.contrib.auth.context_processors.auth',
                                                   u'django.contrib.messages.context_processors.messages',
                                                   u'django.core.context_processors.debug',
                                                   u'django.core.context_processors.i18n',
                                                   u'django.core.context_processors.static',
                                                   u'django.core.context_processors.media',
                                                   u'django.core.context_processors.request',
                                                   u'django.core.context_processors.tz',
                                                   u'mezzanine.conf.context_processors.settings',
                                                   u'mezzanine.pages.context_processors.page')}}]

?: (mezzanine.core.W02) TEMPLATE_DEBUG and DEBUG settings have different values, which may not be what you want. Mezzanine used to fix this for you, but doesn't any more. Update your settings.py to use the TEMPLATES setting to have template debugging controlled by the DEBUG setting.

System check identified 2 issues (0 silenced).
April 17, 2016 - 18:47:16
Django version 1.9.5, using settings 'drumbase.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/home/keiser1080/pypy-5.0.1-linux-armhf-raspbian/lib-python/2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/keiser1080/.virtualenvs/pypy-env/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/keiser1080/.virtualenvs/pypy-env/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/keiser1080/.virtualenvs/pypy-env/site-packages/django/core/handlers/wsgi.py", line 158, in __call__
    self.load_middleware()
  File "/home/keiser1080/.virtualenvs/pypy-env/site-packages/django/core/handlers/base.py", line 51, in load_middleware
    mw_class = import_string(middleware_path)
  File "/home/keiser1080/.virtualenvs/pypy-env/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/home/keiser1080/pypy-5.0.1-linux-armhf-raspbian/lib-python/2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/keiser1080/.virtualenvs/pypy-env/site-packages/mezzanine/pages/middleware.py", line 8, in <module>
    from mezzanine.pages import context_processors, page_processors
  File "/home/keiser1080/.virtualenvs/pypy-env/site-packages/mezzanine/pages/context_processors.py", line 2, in <module>
    from mezzanine.pages.models import Page
  File "/home/keiser1080/.virtualenvs/pypy-env/site-packages/mezzanine/pages/models.py", line 35, in <module>
    class Page(BasePage):
  File "/home/keiser1080/.virtualenvs/pypy-env/site-packages/mezzanine/core/models.py", line 390, in __new__
    return super(OrderableBase, cls).__new__(cls, name, bases, attrs)
  File "/home/keiser1080/.virtualenvs/pypy-env/site-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class mezzanine.pages.models.Page doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
`

**Comment by keiser1080** [comment]
thanks,

it's work now!
