### ISSUE TITLE
ImportError: cannot import name 'patterns' with Django 1.10

### ISSUE THREAD

**Issue by procmail** [stephenmcd/drum#41]
Clean install of drum and mezzanine gives the following error, as Django 1.10 has removed patterns:

`(testDrum) erics-mbp:website eric$ python manage.py createdb
/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/mezzanine/utils/conf.py:56: UserWarning: You haven't defined the ALLOWED_HOSTS settings, which Django requires. Will fall back to the domains configured as sites.
  warn("You haven't defined the ALLOWED_HOSTS settings, which "
/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/mezzanine/accounts/defaults.py:23: UserWarning: Django's AUTH_PROFILE_MODULE setting is deprecated, use Mezzanine's ACCOUNTS_PROFILE_MODEL instead.
  warn("Django's AUTH_PROFILE_MODULE setting is deprecated, use "
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/core/management/base.py", line 353, in execute
    self.check()
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/eric/virtualenv/testDrum/lib/python3.4/site-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/eric/virtualenv/testDrum/website/website/urls.py", line 2, in <module>
    from django.conf.urls import patterns, include, url
ImportError: cannot import name 'patterns'
`

**Comment by stephenmcd** [comment]
https://github.com/stephenmcd/drum/pull/31
